@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Aug 01 20:42:40 +0800 2022
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testfixture_behav -key {Behavioral:sim_1:Functional:testfixture} -tclbatch testfixture.tcl -view C:/Users/HIBIKI/Desktop/New_LAB612_Training/Week2/Graduate_CIC_2022_JAM/2022_grad_cell/JAM/JAM.wcfg -log simulate.log"
call xsim  testfixture_behav -key {Behavioral:sim_1:Functional:testfixture} -tclbatch testfixture.tcl -view C:/Users/HIBIKI/Desktop/New_LAB612_Training/Week2/Graduate_CIC_2022_JAM/2022_grad_cell/JAM/JAM.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
